FROM phusion/baseimage:0.11

COPY appland_dev/pg-repo-key.asc /
RUN echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list\
    && apt-key add /pg-repo-key.asc >/dev/null 2>&1

RUN export DEBIAN_FRONTEND=noninteractive \
    && curl -sL https://deb.nodesource.com/setup_10.x \
      | bash - \
    && apt-add-repository ppa:brightbox/ruby-ng \
    && apt-get update -y \
    && apt-get install -y \
      build-essential \
      zlib1g-dev libxml2 \
      ruby2.6 ruby2.6-dev \
      postgresql-client \
      libpq-dev \
      unattended-upgrades \
      git \
      update-notifier-common \
      vim \
      curl \
      jq \
      tzdata \
      cmake \
      pkg-config \
      libssl-dev \
      nodejs \
    && unset DEBIAN_FRONTEND \
    && mkdir -p /src/appland \
    && gem install -N -v 1.16.3 bundler

WORKDIR /src/appland

ADD Gemfile           .
ADD Gemfile.lock      .
ADD package.json      .
ADD package-lock.json .

RUN bundle \
  && npm install

ENV PORT 3000
ENV TERM xterm

EXPOSE 3000
